name = "BioJournals"
uuid = "3d0cccd5-4094-4651-9195-817eb761c4fe"
authors = ["Ethan Gabriel Leskovec <e.leskovec@campus.unimib.it> and contributors"]
version = "1.0.0-DEV"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"

[compat]
BioSequences = "3.4.1"
DataStructures = "0.18"
FASTX = "1.0.0"
julia = "1.11.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
